services:
  web:
    image: bgtuser/pb:latest
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8003 config.wsgi:application"
    ports:
      - "8003:8003"
    environment:
      - SECRET_KEY=unsafe-development-key
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DB_NAME=pinob_db
      - DB_USER=pinoadmino
      - DB_PASSWORD=pinopazz_intra
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=pinob_db
      - MYSQL_USER=pinoadmino
      - MYSQL_PASSWORD=pinopazz_intra
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data: