version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pb-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pinob_db
      MYSQL_USER: pinoadmino
      MYSQL_PASSWORD: pinopazz_intra
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pb-network

  backend:
    build: ./pb-backend
    image: bgtuser/pb-back:latest
    container_name: pb-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8003:8000"
    volumes:
      - media_data:/app/media
    networks:
      - pb-network
    depends_on:
      - db
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/products/" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: pb_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - pb-network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  frontend:
    build: ./pb-frontend
    image: bgtuser/pb-front:latest
    container_name: pb-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - media_data:/usr/share/nginx/html/media:ro
    networks:
      - pb-network
    depends_on:
      - backend

networks:
  pb-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  media_data:
