version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pb-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pinob_db
      MYSQL_USER: pinoadmino
      MYSQL_PASSWORD: pinopazz_intra
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "pinoadmino", "--password=pinopazz_intra" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pb-network

  backend:
    build: ./pb-backend
    image: bgtuser/pb-back:latest
    container_name: pb-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - media_data:/app/media
    networks:
      - pb-network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./pb-frontend
      args:
        VITE_API_URL: https://pinobite.com
    image: bgtuser/pb-front:latest
    container_name: pb-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - media_data:/usr/share/nginx/html/media:ro
    networks:
      - pb-network
    depends_on:
      - backend

networks:
  pb-network:
    driver: bridge

volumes:
  mysql_data:
  media_data:
