[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:django]
command=python manage.py runserver 0.0.0.0:8003
directory=C:\Users\A\Local Sites\pinobite\Pb\pb-backend
stdout_logfile=/tmp/django.log
stderr_logfile=/tmp/django_error.log
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
environment=DJANGO_SETTINGS_MODULE="config.settings"
