# Generated by Django 6.0.2 on 2026-02-12 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('Recipe', 'Recipe'), ('Lifestyle', 'Lifestyle'), ('News', 'News')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('image', models.URLField(max_length=1000)),
                ('date', models.CharField(max_length=50)),
                ('read_time', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('content', models.JSONField(default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.URLField(max_length=1000)),
                ('summary', models.TextField()),
                ('full_story', models.JSONField(default=list)),
                ('gallery', models.JSONField(default=list)),
                ('featured_products', models.JSONField(default=list)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=1000)),
                ('cta', models.CharField(max_length=50)),
                ('bg_color', models.CharField(max_length=50)),
                ('accent_color', models.CharField(max_length=50)),
                ('blob_color', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('image', models.URLField(max_length=1000)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('description', models.TextField()),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('nutrients', models.JSONField(blank=True, default=list)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.URLField(max_length=1000)),
                ('media_type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=10)),
                ('product_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_str', models.CharField(default='general', max_length=50)),
                ('user_name', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('avatar', models.URLField(max_length=1000)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.product')),
            ],
        ),
    ]
