# Generated by Django 6.0.2 on 2026-02-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='media_url',
            field=models.TextField(),
        ),
    ]
