# Generated by Django 6.0.2 on 2026-02-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorsubmission',
            name='address_details',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='visitorsubmission',
            name='brand_awareness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitorsubmission',
            name='buying_source',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='visitorsubmission',
            name='current_usage',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='visitorsubmission',
            name='flavor_preferences',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='visitorsubmission',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitorsubmission',
            name='review_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='visitorsubmission',
            name='reviewed_product',
            field=models.CharField(default='', max_length=100),
        ),
    ]
