# Generated by Django 6.0.2 on 2026-02-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_blogpost_id_alter_category_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
