# Generated by Django 4.2.16 on 2026-03-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_story_original_drive_url_alter_announcement_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='description',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='background_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_cta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_cta_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='transition_type',
            field=models.CharField(default='fade', max_length=50),
        ),
    ]
