# Generated by Django 4.2.16 on 2026-03-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_story_original_drive_url_alter_announcement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='background_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
