# Generated by Django 4.2.16 on 2026-03-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_heroslide_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_house', models.CharField(max_length=255)),
                ('logo', models.TextField()),
                ('quote', models.TextField()),
                ('author', models.CharField(default='Unknown', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
