# Generated by Django 4.2.16 on 2026-03-29 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_pressupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PressUpdate',
        ),
    ]
