# Generated by Django 4.2.16 on 2026-04-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='full_video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
