# Generated by Django 4.2.16 on 2026-04-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_usageidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fuel_bars_shared',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='impact_participants',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vibe_energy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
