# Generated by Django 4.2.16 on 2026-04-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_event_fuel_bars_shared_event_impact_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
