# Generated by Django 4.2.16 on 2026-04-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_blogpost_is_active_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='mobile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
