# Generated by Django 4.2.16 on 2026-04-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_add_wishlist_share_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='poster_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
