# Generated by Django 4.2.16 on 2026-05-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_blogpost_author_image_blogpost_author_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/authors/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='intro_heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/extra/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tertiary_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/extra/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/bg/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/mobile/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='models_3d/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='full_video_url',
            field=models.FileField(blank=True, null=True, upload_to='stories/full/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='media_url',
            field=models.FileField(blank=True, null=True, upload_to='stories/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='original_drive_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='poster_url',
            field=models.ImageField(blank=True, null=True, upload_to='stories/posters/'),
        ),
        migrations.AlterField(
            model_name='usageidea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='usage_ideas/'),
        ),
    ]
