# Generated by Django 4.2.18 on 2026-05-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_blogpost_created_at_blogpost_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
