# Generated by Django 4.2.16 on 2026-05-20 05:12

from django.db import migrations, models
from django.utils.text import slugify


def populate_product_slugs(apps, schema_editor):
    Product = apps.get_model('api', 'Product')
    for product in Product.objects.all():
        base_slug = slugify(product.name)
        slug = base_slug
        counter = 1
        while Product.objects.filter(slug=slug).exclude(id=product.id).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        product.slug = slug
        product.save(update_fields=['slug'])


def populate_blogpost_slugs(apps, schema_editor):
    BlogPost = apps.get_model('api', 'BlogPost')
    for post in BlogPost.objects.all():
        base_slug = slugify(post.title)
        slug = base_slug
        counter = 1
        while BlogPost.objects.filter(slug=slug).exclude(id=post.id).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        post.slug = slug
        post.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_blogpost_created_at_blogpost_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(populate_product_slugs, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(populate_blogpost_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
