# Generated by Django 4.2.18 on 2026-05-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_add_slug_to_product_and_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
