# Generated by Django 4.2.18 on 2026-05-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_blogpost_created_at_alter_blogpost_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailed_nutrition',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
