# Generated by Django 4.2.16 on 2026-05-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_product_detailed_nutrition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorsubmission',
            name='address_details',
        ),
        migrations.RemoveField(
            model_name='visitorsubmission',
            name='brand_awareness',
        ),
        migrations.RemoveField(
            model_name='visitorsubmission',
            name='buying_source',
        ),
        migrations.RemoveField(
            model_name='visitorsubmission',
            name='current_usage',
        ),
        migrations.RemoveField(
            model_name='visitorsubmission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='visitorsubmission',
            name='flavor_preferences',
        ),
        migrations.RemoveField(
            model_name='visitorsubmission',
            name='marketing_consent',
        ),
        migrations.RemoveField(
            model_name='visitorsubmission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='visitorsubmission',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='visitorsubmission',
            name='review_content',
        ),
        migrations.RemoveField(
            model_name='visitorsubmission',
            name='reviewed_product',
        ),
        migrations.AddField(
            model_name='visitorform',
            name='form_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='visitorform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visitorsubmission',
            name='submission_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
