# Generated by Django 4.2.16 on 2026-05-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_formverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorform',
            name='require_email_verification',
            field=models.BooleanField(default=False),
        ),
    ]
