# Generated by Django 4.2.16 on 2026-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_fix_order_status_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points_deducted',
            field=models.IntegerField(default=0),
        ),
    ]
