# Generated by Django 4.2.16 on 2026-08-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_heroslide_accent_color_and_more'),
        ('api', '0048_add_product_timestamps'),
    ]

    operations = [
    ]
